### ISSUE TITLE
Preview Version

### ISSUE THREAD

**Issue by vertonghenb** [Azure/github-actions#60]
Is it possible to build / deploy using the ASP.NET Core 3.0 previews?

**Comment by xt0rted** [comment]
I setup a workflow doing this. Here's an example of my setup:

```yaml
name: Build & Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          version: 3.0.100-preview8-013656

      - name: Build Site
        run: dotnet build --configuration Release

      - name: Publish Site To Artifacts Folder
        env:
          DOTNET_CONFIGURE_AZURE: 1
        run: dotnet publish --configuration Release --output artifacts

      - name: Package Artifacts
        run: Compress-Archive -Path artifacts\* -DestinationPath artifacts
        shell: pwsh

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts.zip
          path: artifacts.zip

      - name: Publish To Azure
        uses: azure/appservice-actions/webapp@master
        with:
          app-name: app-name
          package: artifacts.zip
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
```

This is my `csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win10-x86</RuntimeIdentifier>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>
</Project>
```
